name: Docker image with Github actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: 
      - ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"
